// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ0x_CRpNpF8bQ7bVgO5_OQ2G-tapAKzo',
    appId: '1:622598352693:web:f1723a97c680bc6c94267c',
    messagingSenderId: '622598352693',
    projectId: 'docapp-aae50',
    authDomain: 'docapp-aae50.firebaseapp.com',
    storageBucket: 'docapp-aae50.appspot.com',
    measurementId: 'G-HHG3XBEHEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi41ZkolUK7g4kgsf4f8OhP3etTEikn6I',
    appId: '1:622598352693:android:8af25913226dcabe94267c',
    messagingSenderId: '622598352693',
    projectId: 'docapp-aae50',
    storageBucket: 'docapp-aae50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMSKY3H1nbW7ZLlqGCYfi_Dck6_tn84AA',
    appId: '1:622598352693:ios:5db5677f35adcc0194267c',
    messagingSenderId: '622598352693',
    projectId: 'docapp-aae50',
    storageBucket: 'docapp-aae50.appspot.com',
    iosClientId: '622598352693-4fsk17vb5ghk6jufi10hc7ggr1bdpq3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.log',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMSKY3H1nbW7ZLlqGCYfi_Dck6_tn84AA',
    appId: '1:622598352693:ios:e5c3fbc21ecbeb4394267c',
    messagingSenderId: '622598352693',
    projectId: 'docapp-aae50',
    storageBucket: 'docapp-aae50.appspot.com',
    iosClientId: '622598352693-nv40iu1q96clbj563nnogplvuh2bfg4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.log.RunnerTests',
  );
}
